apiVersion: v1
kind: ConfigMap
metadata:
  name: ma-config-html
data:
  index.html: |
    <html>
    <head>
      <meta charset="utf-8">
      <title>K8s Training</title>
    </head>
    <body>
      <h1>Bonjour Kubernetes ! ☸️</h1>
      <p>Cette page est propulsée par un ConfigMap.</p>
    </body>
    </html>