apiVersion: apps/v1
kind: Deployment
metadata:
  name: mon-super-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        env:
          # kubectl create secret generic mon-secret-admin --from-literal=password=SuperMotDePasse123
          # kubectl get secret mon-secret-admin -o yaml
          - name: PASSWORD_ADMIN
            valueFrom:
              secretKeyRef:
                name: mon-secret-admin
                key: password
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
        - name: data-persistant
          mountPath: /var/donnees
      volumes:
      - name: html-volume
        configMap:
          name: ma-config-html
      - name: data-persistant
        persistentVolumeClaim:
          claimName: mon-ticket-stockage