apiVersion: v1
kind: ConfigMap
metadata:
  name: ma-config-html
data:
  index.html: |
    <html>
    <head>
      <meta charset="utf-8">
      <title>Helmo World</title>
    </head>
    <body>
      <h1>Site Web Deployé par Helm ! ⎈</h1>
     <p>Ce cluster est maintenant autonome.</p>
    </body>
    </html>