apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mon-ingress-web
spec:
  rules:
  - host: mon-super-site.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mon-service-public
            port:
              number: 80